// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA052ugsm3CmG0sG-QCHKE0cs82Z4Kjd9U',
    appId: '1:28690273038:web:339b8bbdce5fc79d55bd5f',
    messagingSenderId: '28690273038',
    projectId: 'testing-cli-8b24c',
    authDomain: 'testing-cli-8b24c.firebaseapp.com',
    storageBucket: 'testing-cli-8b24c.appspot.com',
    measurementId: 'G-1ZM178Q0VP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSQmf_-CflsLnLIxb3aOUgaZSvlWB62-k',
    appId: '1:28690273038:android:f9128c1621abeb8255bd5f',
    messagingSenderId: '28690273038',
    projectId: 'testing-cli-8b24c',
    storageBucket: 'testing-cli-8b24c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj-XCMY_F-EXPRTYCHuJ1sUCrP06Us-w0',
    appId: '1:28690273038:ios:f101948bb025f3dc55bd5f',
    messagingSenderId: '28690273038',
    projectId: 'testing-cli-8b24c',
    storageBucket: 'testing-cli-8b24c.appspot.com',
    iosBundleId: 'com.technicalhamza.flutterFirebasePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj-XCMY_F-EXPRTYCHuJ1sUCrP06Us-w0',
    appId: '1:28690273038:ios:111d56da210d8a3a55bd5f',
    messagingSenderId: '28690273038',
    projectId: 'testing-cli-8b24c',
    storageBucket: 'testing-cli-8b24c.appspot.com',
    iosBundleId: 'com.technicalhamza.flutterFirebasePractice.RunnerTests',
  );
}
